name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Login, build and push the Docker image
      run: |
        docker login --username nathanlemaire91 --password ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build . --file Dockerfile --tag ghcr.io/nathanlemaire91/heart_diseas_prediction:latest,
        docker push ghcr.io/nathanlemaire91/heart_disease_prediction:latest
